### ISSUE TITLE
Identically Recurring Elements is defined but unused

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#176]
In https://github.com/Matroska-Org/ebml-specification/blob/master/specification.markdown#identically-recurring-elements we defined Identically Recurring Elements but this term is never used. IIRC this was defined to anticipate use in streams where some Elements may be recur in excess of maxOccurs, such as Tracks in a live stream. Should we use this? Which elements would be relevant? Am guessing there's just a few Top Level Elements where this is relevant.

**Comment by dericed** [comment]
I'd propose that `Tracks` have `recurring=true`, maybe `Info` and `Tags`. Is there any other need for repetition of Elements within a stream?

**Comment by mbunkus** [comment]
I'd argue that those level 1 elements that actually make a difference during playback should have `recurring=true`. This obviously means `Info`, `Tracks` with a strong vote for `Chapters` (segment/chapter linking has obvious implications on playback). Even `Attachments` might make the list (due to fonts for subtitle tracks). However, `Tags` doesn't in my opinion as it only contains informational data that isn't required for playback.

**Comment by robUx4** [comment]
I wouldn't put `Attachments` in there they are not needed for playback and are quite big.

Also features of EBML may not necessarily be used by Matroska, it's not a problem.

**Comment by dericed** [comment]
Two separate issues here:
1. The `recurring` attribute is not defined as part of the EBML Schema (EBML issue). I'll resolve this next.
2. The `recurring' attribute is not used in the Matroska EBML Schema (Matroska issues). To be resolved after 1.
