### ISSUE TITLE
add section for handling bad data

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#48]
For instance what to do when finding a bad CRC value or a duplicate Element that isn't allowed to appear multiple times.

**Comment by dericed** [comment]
nudging on this as it's worth offering guidance on these scenarios. If reading a master element which contains a CRC-32 element which stores an invalid value, what should be reader do: ignore the master element, reject the file, read it anyhow?
If a 2nd occurrence of a maxoccurs=1 element is found, which should take precedence?

**Comment by retokromer** [comment]
One possible answer from the real world (our own reading tools):

- give an error message having the options: try to read anyway or abort;
- if additional 2nd, then give an error message and simply ignore 2nd.

**Comment by robUx4** [comment]
If a master element has a CRC-32, sub elements may have some too. If these are valid the data for these can be used. The rest of the master data should no be used. It's not that big a deal to handle since you only know if the CRC-32 matches when you have read all the data. So you can tell which parts are OK and which are not.
Not easy to phrase properly though.
