### ISSUE TITLE
Abstract / Introduction section

### ISSUE THREAD

**Issue by epiil** [Matroska-Org/ebml-specification#5]
As it stands the EBML specification lacks an Introduction section, which is an IETF requirement. 

RFC2223 describes the Introduction Section as follows:

"  Each RFC should have an Introduction section that (among other things) explains the motivation for the RFC and (if appropriate) describes the applicability of the protocol described."

"Normally, this will be the "abstract" section from the Internet Draft.  If the RFC is not based on an I-D, other possibilities are:

Protocol

            This protocol is intended to provide the bla-bla service,
            and be used between clients and servers on host computers.
            Typically the clients are on workstation hosts and the
            servers on mainframe hosts.

            or

            This protocol is intended to provide the bla-bla service,
            and be used between special purpose units such as terminal
            servers or routers and a monitoring host.

Discussion

            The purpose of this RFC is to focus discussion on particular
            problems in the Internet and possible methods of solution.
            No proposed solutions in this document are intended as
            standards for the Internet.  Rather, it is hoped that a
            general consensus will emerge as to the appropriate solution
            to such problems, leading eventually to the adoption of
            standards.

         Interest

            This RFC is being distributed to members of the Internet
            community in order to solicit their reactions to the
            proposals contained in it.  While the issues discussed may
            not be directly relevant to the research problems of the
            Internet, they may be interesting to a number of researchers
            and implementers.

         Status Report

            In response to the need for maintenance of current
            information about the status and progress of various
            projects in the Internet community, this RFC is issued for
            the benefit of community members.  The information contained
            in this document is accurate as of the date of publication,
            but is subject to change.  Subsequent RFCs will reflect such
            changes.

      These paragraphs need not be followed word for word, but the
      general intent of the RFC must be made clear."

**Comment by epiil** [comment]
Sorry, here's the language from the current style guide, RFC7322:

4.8.  Body of the Memo

   Following the TOC is the body of the memo.

   Each RFC must include an Introduction section that (among other
   things) explains the motivation for the RFC and (if appropriate)
   describes the applicability of the document, e.g., whether it
   specifies a protocol, provides a discussion of some problem, is
   simply of interest to the Internet community, or provides a status
   report on some activity.  The body of the memo and the Abstract must
   be self-contained and separable.  This may result in some duplication
   of text between the Abstract and the Introduction; this is
   acceptable.

4.8.1.  Introduction Section

   The Introduction section should always be the first section following
   the TOC (except in the case of MIB module documents).  While
   "Introduction" is recommended, authors may choose alternate titles
   such as "Overview" or "Background".  These alternates are acceptable.

**Comment by mbunkus** [comment]
So we have to talk about our intentions and goals back then, I guess. From my point of view:

- We wanted a container for any kind of multimedia content
- That container should be: somewhat space-efficient (therefore a binary format and not a textual representation); easily extensible with new elements catering to new requirements; easy to parse (again a binary format); not limited by fixed-width fields (hence the use of VINTs).
- We recognized the idea behind HTML and XML as a good one: separate structure and meaning/semantics allowing the same structural layer to be used with multiple, possibly widely differing semantic layers.
- Hence we decided to create a separate layer for the structure: EBML.
- We chose a simple tag/length/value based approach because it's a well-known and proven concept that's easy to parse. Additionally it allows to parse the data only partially if you're not interested in it by reading the tag/length and then skipping the value.
- We chose a hierarchical format because a lot of data in the audio/video world is hierarchical. Also it allows a reader to skip over unwanted content quickly.

**Comment by robUx4** [comment]
And the UTF like coding was chosen because it saves space compared to a fixed size for all IDs and length as is generally the case with TLV formats (Type Length Value).

From the RFC quote, it seems we should only describe the goal in the introduction though. Not the rationale behind the choices.

**Comment by dericed** [comment]
After https://github.com/Matroska-Org/ebml-specification/commit/8f5f4a77c7bedd7a838a5c0fa7b64caa7cee83a2, is there anything else to do on this issue?

**Comment by mbunkus** [comment]
None that I can think of.
