### ISSUE TITLE
Security Considerations section

### ISSUE THREAD

**Issue by epiil** [Matroska-Org/ebml-specification#6]
From RFC7322:

4.8.5.  Security Considerations Section

   All RFCs must contain a section that discusses the security
   considerations relevant to the specification; see "Guidelines for
   Writing RFC Text on Security Considerations" [BCP72] for more
   information. - http://www.rfc-editor.org/info/bcp72

**Comment by mbunkus** [comment]
This is a somewhat harder one. I've skimmed through the best common practices you've linked to. Some points that popped into my mind:

- EBML itself does not offer any kind of security. It has nothing to do with authentication, it dose not provide confidentiality, only marginally useful and effective data integrity options (CRC elements).
- EBML does not provide any kind of authorization.
- Even if the semantic layer offers and kind of encryption EBML itself leaks information, at the least the sematic layer used via the DocType element, but also certain information about the structure from the elements (you can derive the presence of EBML elements even with an unknown semantic layer with a heuristic approach; not without errors, of course, but with a certain degree of confidence).
- Attacks on an EBML reader may include:
  - invalid IDs (longer than the max length stated in the EBML header; not encoded in the shortest-possible way; usage of reserved values)
  - Invalidly encoded lengths (similar to the IDs)
  - Invalid lengths (e.g. extending beyond the scope of the parent element; possibly triggering access-out-of-bounds issues)
  - Very high lengths in order to force out-of-memory situations resulting in a denial of service, access-out-of-bounds issues etc.
  - Missing mandatory elements (even EBML has mandatory elements, not just Matroska)
  - Usage of \0 characters in EbmlString elements
  - Usage of invalid UTF-8 encoding in EbmlUnicodeStrings (e.g. in order to trigger acces-out-of-bounds or buffer overflow issues)
  - Usage of invalid data in date elements

**Comment by robUx4** [comment]
I think @mbunkus covered all the attacks I could think of. I was wondering if it's possible to break things with an infinite size but I can't think of any.
That's almost scary to see all possible attacks on such a basic format. Not sure libebml even covers all of them.

**Comment by dericed** [comment]
@mbunkus, Is your [comment](https://github.com/Matroska-Org/ebml-specification/issues/6#issuecomment-99937237) above still up to date? Could you draft a Security Consideration section for the EBML spec?  RFC Guidelines for the Security Consideration section are [here](https://tools.ietf.org/html/rfc3552).

**Comment by mbunkus** [comment]
I cannot think of anything to add to that list at the moment, and all points above remain valid. So it is up to date from my point of view. I can write something up in the next couple of days.

**Comment by dericed** [comment]
going to close, since we have https://github.com/Matroska-Org/ebml-specification/commit/75ff1ed66f1857ae710a9bb95ad3b04b5dfb79b7

**Comment by dericed** [comment]
ooops, i'm not authorized to close this issue. Ping @mbunkus.
