### ISSUE TITLE
document why a Master Element should include junk data

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#92]
From Tim's review:

> Can you describe reasons someone might reasonably violate these SHOULDs? You've specified _when_ they are allowed to, but not _why_. Is the "is permitted" case the only case in which it is permitted? If so, you should structure the normative language to make that clear. What does it mean for EBML to be "used in transmission or streaming"? If someone sends you an EBML document over HTTP, and you save it to disk, are you required to strip out any non-element data from Master Elements?

Referenced section is in the Master Element definition. I suggest working on the clarification branch since that also affects this area.

**Comment by mbunkus** [comment]
I think what we want to allow is that there be junk in the file, and players (consumers) should be able to deal with that. They should not be allowed to simply reject a file because there is junk in it. Why? Because both transmission and storage are prone to errors (e.g. media errors or lost packets during transmission).

Additionally a player should only be required to skip that data until it finds a valid element again (that's what players will do anyway already in order to be error resilient).

What I wouldn't want to allow is that applications creating EBML files (a producer) intentionally write junk.

Therefore we may have to spell out different requirements depending on the program's role (producer or consumer) in the definition of `Master Element`.

**Comment by robUx4** [comment]
One man's junk is another man's treasure.

What type of junk are we talking about anyway ? EBML data from an unknown Doctype or data that don't appear like EBML at all ? In no case SHOULD the junk be removed from the file received, unless you're remuxing. It would screw up the parent element(s) size(s). If one really want to not store unknown data they can always void it (unless it's a single byte).

**Comment by dericed** [comment]
IMO this was resolved with https://github.com/Matroska-Org/ebml-specification/commit/2e01b6b6fab8fc30381b05bd9fbeac6ca233df02 and a few subsequent revisions to that paragraph. I'm going to close. Re-open if you disagree.
