### ISSUE TITLE
consider change Void from 0+ to 1+

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#93]
A lot of language of the ebml spec could be simplified if Void was not allowed to occur at level 0. I'm scanning a large Matroska collection from archive.org to see if Void at level 0 ever occurs. So far 3864 mkv files tested with only EBML and Segment at Level 0. Will report back when the test is done.

**Comment by dericed** [comment]
I found a Level 0 Void element! But it's because the file is really messed up. The Segment element is zero-sized, thus the subsequent element is also at Level 0 rather within the Segment element at Level 1. Also mkvalidator throws 143,429 lines of errors with this file.

I tested 82,935 Matroska files on the Internet Archive and only one file had a Void Element at Level 0: [The.Simpsons.S06.E05.www.VideoBaran.net.mkv](http://www.archive.org/download/vip.videobaran1.com/The.Simpsons/06/The.Simpsons.S06.E05.www.VideoBaran.net.mkv). This file was written by ... "mkvmerge v2.4.1 ('Use Me') built on Dec  5 2008 18:30:05" :-O

Thus I propose setting Void to be Level 1+, so that the only valid Level 0 elements are the EBML Header and the Root Element.

**Comment by retokromer** [comment]
:+1:

**Comment by mbunkus** [comment]
I'm definitely fine with the change. Consider that file you've found to be either written by a buggy version or to have been damaged.

**Comment by dericed** [comment]
Will do after the clarifications PR since in addition to changing Void to 1+, there are many sentences about Top-Level Elements and Root Element to be cleaned up.

**Comment by robUx4** [comment]
Ah while reading PR #101 I was wondering if that was necessary to have level 0 for `Void`. One case I could think of is `EBML Documents` concatenated together and you want to void one of the document in the `EBML Stream`. Obviously noone uses concatenated EBML Documents and even less need to invalidate one part of that file. So you're not going to find much samples.

Consider a 20TB concatenated EBML Documents file. You don't want to have to copy/rewrite a whole 20TB of data just to cancel a part. Although It's possible to void the `Segment` data rather than the `Segment` itself. It's a bit less elegant (is a `Segment with just a `Void` element valid?).

I see what we would lose but what do we gain from this change ?

**Comment by dericed** [comment]
The case of voiding an entire EBML Document from an EBML Stream sounds useful, but when I try to place a Void in between the EBML Header and Segment, then mkvalidator, ffmpeg, etc all complain.

**Comment by dericed** [comment]
[sample with Level 0 Void in between EBML Header and Segment](https://github.com/dericed/matroska-test-files/raw/fd7f4482b2bd70fe3cb224ce9b4644349bd65532/invalid_ebml/level_0_void.mkv)

**Comment by robUx4** [comment]
Most tools/players don't deal well with concatenated `EBML Documents`. Most people were not aware it was possible and/or existed. But it will be in the speficiations so we should make use of it.

So do we close this issue ?

**Comment by dericed** [comment]
Yes it was considered and I think that finds not enough for the limitation. I not as well that whitespace in XML in between the XML Declaration and XML Body appears to be allowed, so a VOID between the EBML Header and Segment seems to be the equivalent.
