### ISSUE TITLE
review method to determine end of unknown-size element

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#94]
Tim asked in cellar review:

> If maxOccurs is a positive integer, and maxOccurs instances of the element have already been encountered within a Master Element with an unknown size, is the another instance of this element considered "...the beginning of the next element that is not a valid sub-element of that Master-element”?

For instance if Segment is unknown sized and knowing the Attachments can only occur once within the Segment, then with this structure:

``` xml
<Segment>
<Attachments/>
<Attachments/>
```

Is the Segment expected to end at when the second occurrence of <Attachments> is read, since a 2nd expression of Attachments "is not a valid sub-element of that Master-element"?

**Comment by mbunkus** [comment]
Ugh, that's ugly. At the moment I'm leaning slightly in the direction of saying that no, this doesn't signal the end of the unknown-sized parent. Solely so that consumers aren't required to track the times a child element has already occurred within its parent.

I'd rather read "…a valid sub-element…" solely from the perspective of whether an element is generally allowed as a child of that parent element. Though I admit this is a bit inconsistent.

**Comment by robUx4** [comment]
No it doesn't mark the end of the unknown sized parent. The semantic level has priority over the number of elements that are valid. Although it's not written that way, the only ways to end an unknown size element is the end of the file, or an element of the same level or upper level.

**Comment by dericed** [comment]
i rewrote this to:

> The end of an `Unknown-Sized Element` is determined by whichever comes first: the end of the file or the beginning of the next `EBML Element`, defined by this document or the corresponding `EBML Schema`, that is not independently valid as Descendent Element of the `Unknown-Sized Element`.

as I think that clarifies the Segment/Attachment/Attachment example above.

**Comment by dericed** [comment]
closing per https://github.com/Matroska-Org/ebml-specification/issues/133
